language: node_js
node_js:
  - 11
os: linux
script:
  - npm run build
deploy:
  provider: pages
  cleanup: true
  local_dir: public
  committer_from_gh: true
  keep_history: true
  token:  $GH_PAT
  on:
    branch: production
notifications:
  email: false
